config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :voters
  resources :proposals
  resources :polls
  resources :items
  
  get '/polls/:id/results', to: "polls#results", as: :results_polls
  get '/polls/:id/vote', to: "polls#votes", as: :votes_polls
  post '/polls/:id/vote', to: "polls#votes!"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/poll.rb
class Poll < ApplicationRecord
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy, :results, :votes, :votes!]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # GET /polls/1/results
  def results
    proposals = Proposal.where(poll_id: @poll.id)
    @items = Item.where(id: proposals.pluck(:item_id))
    @votes = get_votes_for_poll(@poll)
    @voters = Voter.where(id: @votes.pluck(:voter_id))
  end

  # GET /polls/1/vote
  def votes
    @items = Item.all

    # TODO: Fill model with data
  end

  # POST /polls/1/votes
  def votes!
    if params[:voter_id].nil? or params[:voter_id] == ''
      respond_to do |format|
        format.html { redirect_to votes_polls_path, notice: 'Wähler auswählen!' }
        format.json { render status: :unprocessable_entity }
      end
    else
      voter_id = params[:voter_id].to_i

      params.each do |key, preference_value|
        if /preference_(\d+)/.match(key)
          item_id = $1.to_i
          preference = preference_value.to_sym

          proposal = Proposal.find_by(poll_id: @poll.id, item_id: item_id)

          if preference != :none
            if proposal.nil?
              puts "Cannot find proposal with poll_id #{@poll.id} and item_id #{item_id}. Creating one."

              proposal = Proposal.new({
                poll_id: @poll.id,
                item_id: item_id
              })
              proposal.save!
            end

            vote = Vote.find_by(voter_id: voter_id, proposal_id: proposal.id)

            if vote.nil?
              vote = Vote.new({
                voter_id: voter_id,
                proposal_id: proposal.id,
                preference: preference
              })

              vote.save!
            else
              vote.update!({
                voter_id: voter_id,
                proposal_id: proposal.id,
                preference: preference
              })
            end
          else
            # No preference -> delete vote if it exists
            if !proposal.nil?
              vote = Vote.find_by(voter_id: voter_id, proposal_id: proposal.id)

              if !vote.nil?
                vote.destroy
              end
            end
          end
        end
      end

      respond_to do |format|
        format.html { redirect_to polls_url, notice: 'Erfolgreich abgestimmt.' }
        format.json { head :no_content }
      end
    end
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:name, :description, :status, :started_at, :concluded_at)
    end

    # TODO: Should prob. be inside a service / helper of some kind?
    def get_votes_for_poll(poll)
      proposal_ids = Proposal.where(poll_id: poll.id).pluck(:id)

      Vote.where(proposal_id: proposal_ids)
    end
end

app/helpers/polls_helper.rb
module PollsHelper
  def get_votes_for_voter(votes, voter)
    votes.where(voter_id: voter.id)
  end

  def get_vote_preference_for_poll_and_voter_and_item(poll, voter, item)
    proposal_id = Proposal.where(poll_id: poll.id, item_id: item.id).pluck(:id).first

    vote = Vote.where(voter_id: voter.id, proposal_id: proposal_id).first

    if vote.nil?
      :hide
    else
      vote.preference
    end
  end
end

app/views/polls/_form.html.erb
<div class="row">
  <%= form_with(model: poll, local: true, class: "col s12") do |form| %>
    <% if poll.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

        <ul>
        <% poll.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="input-field col s6">
        <%= form.text_field :name, id: :poll_name %>
        <%= form.label :name %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= form.text_area :description, id: :poll_description, class: "materialize-textarea" %>
        <%= form.label :description, 'Beschreibung' %>
      </div>
    </div>

    <!-- <div class="row">
      <div class="input-field col s6">
        <%= form.text_field :status, id: :poll_status %>
        <%= form.label :status %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= form.text_field :started_at, id: :poll_started_at, class: "datepicker" %>
        <%= form.label :started_at %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= form.text_field :concluded_at, id: :poll_concluded_at, class: "datepicker" %>
        <%= form.label :concluded_at %>
      </div>
    </div> -->

    <div class="actions">
      <%= form.submit 'Speichern', :class => 'waves-effect waves-light btn' %>
    </div>
  <% end %>
</div>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Anzeigen', @poll %> |
<%= link_to 'Zurück', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Umfragen</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Beschreibung</th>
      <!-- <th>Status</th>
      <th>Started at</th>
      <th>Concluded at</th> -->
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @polls.order(:name).reverse_order.each do |poll| %>
      <tr>
        <td><%= poll.name %></td>
        <td><%= poll.description %></td>
        <!-- <td><%= poll.status %></td>
        <td><%= poll.started_at %></td>
        <td><%= poll.concluded_at %></td>
        <<td><%= link_to 'Anzeigen', poll %></td>-->
        <td><%= link_to 'Ändern', edit_poll_path(poll) %></td>
        <td><%= link_to 'Löschen', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Abstimmen', votes_polls_path(poll) %></td>
        <td><%= link_to 'Ergebnisse', results_polls_path(poll) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neue Umfrage', new_poll_path %>

app/views/polls/new.html.erb
<h1>Neue Umfrage</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Zurück', polls_path %>

app/views/polls/results.html.erb
<p id="notice"><%= notice %></p>

<h1>Ergebnisse zur Umfrage '<%= @poll.name %>'</h1>

<table>
  <thead>
    <tr>
      <th>Wähler</th>
      <% @items.each do |item| %>
        <th><%= item.name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @voters.each do |voter| %>
    <tr>
      <td><%= voter.name %></td>
      <% @items.each do |item| %>
        <% preference = get_vote_preference_for_poll_and_voter_and_item(@poll, voter, item)
           translated_preference = translate_preference preference
           colorized_preference = colorize_preference preference %>
        <td style="background: <%= colorized_preference %>"><%= translate_preference(get_vote_preference_for_poll_and_voter_and_item(@poll, voter, item)) %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<%# <div id="wheelDiv" style="width: 400px; height: 400px;"></div> %>

<%= link_to 'Zurück', polls_path %>

<%# <script type="text/javascript">
  var wheel = new wheelnav('wheelDiv');
  wheel.spreaderEnable = true;
  wheel.colors = colorpalette.oceanfive;
  wheel.slicePathFunction = slicePath().LineSlice;
  wheel.createWheel(['default', 'enable', 'radius', 'attrs', 'percent']);
</script> %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @poll.name %>
</p>

<p>
  <strong>Beschreibung:</strong>
  <%= @poll.description %>
</p>

<!-- <p>
  <strong>Status:</strong>
  <%= @poll.status %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @poll.started_at %>
</p>

<p>
  <strong>Concluded at:</strong>
  <%= @poll.concluded_at %>
</p> -->

<%= link_to 'Ändern', edit_poll_path(@poll) %> |
<%= link_to 'Zurück', polls_path %>

app/views/polls/votes.html.erb
<%= form_with(local: true) do |form| %>
  <!-- TODO: better error handling. Oh my God, this gets all so ugly so fast. -->
  <p id="notice" style="color: red !important"><%= notice %></p>

  <h1>Für '<%= @poll.name %>' abstimmen</h1>

  <div class="card lime lighten-3">
    <div class="card-content">
      <div class="field">
        <%= form.label :voter_id %>
        <%= form.collection_select(:voter_id, Voter.order(:name), :id, :name, :prompt => 'Bitte wählen') %>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-content">
      <table>
        <thead>
          <tr>
            <th>Ort</th>
            <th>Präferenz</th>
          </tr>
        </thead>
        <tbody>
          <% @items.order(:name).each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <td>
                <div class="field">
                  <!-- TODO: This is so super bad code style. But I don't know what the "rails way" would be like -->
                  <div class="chip">
                    <%= form.radio_button("preference_#{item.id}".to_sym, :very_positive, id: "preference_very_positive_#{item.id}".to_sym) %>
                    <label class="preference-option" for="<%= "preference_very_positive_#{item.id}" %>"><%= translate_preference(:very_positive) %></label>
                  </div>
                  
                  <div class="chip">
                    <%= form.radio_button("preference_#{item.id}".to_sym, :positive, id: "preference_positive_#{item.id}".to_sym) %>
                    <label class="preference-option" for="<%= "preference_positive_#{item.id}" %>"><%= translate_preference(:positive) %></label>
                  </div>
                  
                  <div class="chip">
                    <%= form.radio_button("preference_#{item.id}".to_sym, :neutral, id: "preference_neutral_#{item.id}".to_sym) %>
                    <label class="preference-option" for="<%= "preference_neutral_#{item.id}" %>"><%= translate_preference(:neutral) %></label>
                  </div>
                  
                  <div class="chip">
                    <%= form.radio_button("preference_#{item.id}".to_sym, :negative, id: "preference_negative_#{item.id}".to_sym) %>
                    <label class="preference-option" for="<%= "preference_negative_#{item.id}" %>"><%= translate_preference(:negative) %></label>
                  </div>
                  
                  <div class="chip">
                    <%= form.radio_button("preference_#{item.id}".to_sym, :very_negative, id: "preference_very_negative_#{item.id}".to_sym) %>
                    <label class="preference-option" for="<%= "preference_very_negative_#{item.id}" %>"><%= translate_preference(:very_negative) %></label>
                  </div>

                  <!-- TODO: Maybe use toggleable buttons instead? -->
                  <%= form.radio_button("preference_#{item.id}".to_sym, :none, id: "preference_none_#{item.id}".to_sym, checked: true) %>
                  <label for="<%= "preference_none_#{item.id}" %>">Enthalten</label>
              </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Speichern', :class => 'waves-effect waves-light btn' %>

    <%= link_to 'Zurück', polls_path %>
  </div>
<% end %>