config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :voters
  resources :proposals
  resources :polls
  resources :items
  
  get '/polls/:id/results', to: "polls#results", as: :results_polls
  get '/polls/:id/vote', to: "polls#votes", as: :votes_polls
  post '/polls/:id/vote', to: "polls#votes!"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :poll
  belongs_to :item
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:poll_id, :item_id)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= form_with(model: proposal, local: true) do |form| %>
  <% if proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% proposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :poll_id %>
    <%= form.collection_select(:poll_id, Poll.order(:name), :id, :name, :prompt => 'Bitte wählen') %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.collection_select(:item_id, Item.order(:name), :id, :name, :prompt => 'Bitte wählen') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proposals</h1>

<table>
  <thead>
    <tr>
      <th>Poll</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.poll.name %></td>
        <td><%= proposal.item.name %></td>
        <td><%= link_to 'Show', proposal %></td>
        <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposal', new_proposal_path %>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>

<%= render 'form', proposal: @proposal %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poll:</strong>
  <%= @proposal.poll %>
</p>

<p>
  <strong>Item:</strong>
  <%= @proposal.item %>
</p>

<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>