config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :voters
  resources :proposals
  resources :polls
  resources :items
  
  get '/polls/:id/results', to: "polls#results", as: :results_polls
  get '/polls/:id/vote', to: "polls#votes", as: :votes_polls
  post '/polls/:id/vote', to: "polls#votes!"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/vote.rb
class Vote < ApplicationRecord
  # TODO: Must convert to String as input is a String and not a symbol. What is a better way?!
  @allowed_preferences = [
    :very_positive.to_s,
    :positive.to_s,
    :neutral.to_s,
    :negative.to_s,
    :very_negative.to_s
  ]

  belongs_to :proposal
  belongs_to :voter

  validates :voter_id, uniqueness: {scope: :proposal_id}
  validates :proposal_id, uniqueness: {scope: :voter_id}
  validates :preference, inclusion: @allowed_preferences
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    # TODO: If combination voter poll item is already present -> error (user should edit)

    poll_id = vote_params[:poll_id].to_i
    item_id = vote_params[:item_id].to_i

    proposal = Proposal.find_by(poll_id: poll_id, item_id: item_id)
  
    if proposal.nil?
      puts "Cannot find proposal with poll_id #{poll_id} and item_id #{item_id}. Creating one."

      proposal = Proposal.new({
        poll_id: poll_id,
        item_id: item_id
      })
      proposal.save
    end

    @vote = Vote.new({
      voter_id: vote_params[:voter_id],
      proposal_id: proposal.id,
      preference: vote_params[:preference]
    })

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    # TODO: Copy create code and adjust?

    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])

      proposal = Proposal.find(@vote.proposal_id)

      @poll_id = proposal.poll_id
      @item_id = proposal.item_id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:poll_id, :item_id, :voter_id, :preference)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
  def get_poll_for_proposal(proposal)
    Poll.find(proposal.poll_id)
  end

  def get_item_for_proposal(proposal)
    Item.find(proposal.item_id)
  end

  # TODO: Use real I18N
  def translate_preference(preference)
    pref = preference.to_sym

    case pref
    when :very_positive
      'Mein Favorit'
    when :positive
      'Gerne'
    when :neutral
      'Ist OK'
    when :negative
      'Eher nicht'
    when :very_negative
      'Auf keinen Fall'
    when :unknown
      'Unbekannter Wert'
    else
      ''
    end
  end

  def colorize_preference(preference)
    pref = preference.to_sym

    case pref
    when :very_positive
      '#5f5'
    when :positive
      '#bfb'
    when :neutral
      '#eee'
    when :negative
      '#fbb'
    when :very_negative
      '#f55'
    when :unknown
      '#fff'
    else
      '#fff'
    end
  end
end

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :voter_id %>
    <%= form.collection_select(:voter_id, Voter.order(:name), :id, :name, :prompt => 'Bitte wählen') %>
  </div>

  <div class="field">
    <%= form.label :poll_id %>
    <%= form.collection_select(:poll_id, Poll.order(:name), :id, :name, :prompt => 'Bitte wählen') %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.collection_select(:item_id, Item.order(:name), :id, :name, :prompt => 'Bitte wählen') %>
  </div>

  <div class="field">
    <%= form.radio_button(:preference, :very_positive, id: :preference_very_positive) %>
    <label for="preference_very_positive"><%= translate_preference(:very_positive) %></label>
    
    <%= form.radio_button(:preference, :positive, id: :preference_positive) %>
    <label for="preference_positive"><%= translate_preference(:positive) %></label>
    
    <%= form.radio_button(:preference, :neutral, id: :preference_neutral, checked: true) %>
    <label for="preference_neutral"><%= translate_preference(:neutral) %></label>
    
    <%= form.radio_button(:preference, :negative, id: :preference_negative) %>
    <label for="preference_negative"><%= translate_preference(:negative) %></label>
    
    <%= form.radio_button(:preference, :very_negative, id: :preference_very_negative) %>
    <label for="preference_very_negative"><%= translate_preference(:very_negative) %></label>
  </div>

  <div class="actions">
    <%= form.submit 'Speichern', :class => 'waves-effect waves-light btn' %>
  </div>

  Poll Id: <%= @poll_id %><br />
  Item Id: <%= @item_id %>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abstimmungen</h1>

<div class="row">
  <div class="col s12 m4 offset-m4">
    <div class="card amber">
      <div class="card-image">
        <!-- <img src="http://s2.quickmeme.com/img/fa/fa6eb20c1de5f0b0378e7bdef21845fcc47e5504a01f5c827e78fbb3ae907e03.jpg"> -->
        <img src="http://i.imgur.com/WN8iGfd.png">
      </div>
      <div class="card-content">
        <span class="card-title">Hinweis</span>
        <p>Dieser Bereich wird bald entfernt werden.</p>
        <p>Bitte unter '<%= link_to 'Umfragen', polls_path %>' abstimmen und dort die Ergebnisse einsehen!</p>
      </div>
    </div>
  </div>
</div>

<!-- <table>
  <thead>
    <tr>
      <th>Umfrage</th>
      <th>Item</th>
      <th>Wähler</th>
      <th>Präferenz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= get_poll_for_proposal(vote.proposal).name %></td>
        <td><%= get_item_for_proposal(vote.proposal).name %></td>
        <td><%= vote.voter.name %></td>
        <td><%= translate_preference vote.preference %></td>
        <td><%= link_to 'Anzeigen', vote %></td>
        <td><%= link_to 'Editieren', edit_vote_path(vote) %></td>
        <td><%= link_to 'Löschen', vote, method: :delete, data: { confirm: 'Bist du sicher?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neue Abstimmung', new_vote_path %> -->

app/views/votes/new.html.erb
<h1>Neue Abstimmung</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Zurück', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proposal:</strong>
  <%= @vote.proposal %>
</p>

<p>
  <strong>Voter:</strong>
  <%= @vote.voter %>
</p>

<p>
  <strong>Preference:</strong>
  <%= translate_preference @vote.preference %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>