config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :voters
  resources :proposals
  resources :polls
  resources :items
  
  get '/polls/:id/results', to: "polls#results", as: :results_polls
  get '/polls/:id/vote', to: "polls#votes", as: :votes_polls
  post '/polls/:id/vote', to: "polls#votes!"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Time2eat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Time2Eat</a>
          <a href="#" data-activates="mobile-nav" class="right button-collapse"><i class="material-icons">menu</i></a>
          <ul id="nav" class="right hide-on-med-and-down">
            <li><%= link_to 'Umfragen', polls_path %></li>
            <li><%= link_to 'Items', items_path %></li>
            <li><%= link_to 'Abstimmungen', votes_path %></li>
            <li><%= link_to 'Wähler', voters_path %></li>
          </ul>
          <ul id="mobile-nav" class="right side-nav">
            <li><%= link_to 'Umfragen', polls_path %></li>
            <li><%= link_to 'Items', items_path %></li>
            <li><%= link_to 'Abstimmungen', votes_path %></li>
            <li><%= link_to 'Wähler', voters_path %></li>
          </ul>
        </div>
      </nav>

      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content">
              <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <script>
      $(document).ready(function() {
        $('select').material_select();

        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year,
            today: 'Heute',
            clear: 'Leeren',
            close: 'Ok',
            closeOnSelect: false // Close upon selecting a date,
        });

        $(".button-collapse").sideNav({
          menuWidth: 300, // Default is 300
          edge: 'right', // Choose the horizontal origin
          closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
          draggable: true, // Choose whether you can drag to open on touch screens,
          onOpen: function(el) {  }, // A function to be called when sideNav is opened
          onClose: function(el) {  }, // A function to be called when sideNav is closed
        });
    });
    </script>
  </body>
</html>